M48
; DRILL file KiCad 10.0.3 date 2026-09-11T14:12:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T14:12:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X48.895Y-78.7
X50.165Y-30.44
X100.965Y-45.68
X100.965Y-73.62
M30
